### ISSUE TITLE
Criar componente Criar Playlist

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Frontend#14]
@pdaniel37 commented on [Sat May 11 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Backend/issues/48)

**Eu como** usuário
**Desejo** criar uma playlist
**Para que** seja possível escutar música em grupo

**Descrição:**
Criar barra de pesquisa, onde seja possível procurar músicas e adiciona-las a uma playlist para que seja possível escutar músicas em grupo

**Critérios de aceitação**
- Adicionar música em uma playlist
- Buscar músicas
- obedecer paleta de cores

**Task**
- [ ] Criar componente barra de pesquisa
- [ ] Criar componente de listar músicas

**Comment by oliveiraMarcelo** [comment]
move issue to front-end

**Comment by pdaniel37** [comment]
ultimo commit dessa issue 9793980400c374590c93cb5fd60289cb318816e4.
