### ISSUE TITLE
Criar stylesheet padrão

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Frontend#21]
**Eu como** desenvolvedor
**Desejo** importar um stylesheet padrão para usar nos componentes
**Para que** padronizar o estilo visual da aplicação

**Descrição:**
Criar um stylesheet padrão para ser usado nos botões, text fields, texto, etc.

**Critérios de aceitação**
 * Seguir folha de estilo
 * Seguir paleta de cores

**Task**
- [x] botões
- [x] text fields
- [x] texto
- [x] títulos

**Comment by nicaloribeiro** [comment]
Style sheet para botões criado.
Pareamento presencial realizado com @pdaniel37
